In [33]:
# 기본 라이브러리
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 그래프 기본 테마 설정
# https://coldbrown.co.kr/2023/07/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%8B%A4%EC%A0%84%ED%8E%B8-08-seaborn-sns-set%EC%9D%84-%ED%86%B5%ED%95%B4-%EC%8A%A4%ED%83%80%EC%9D%BC-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0/
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 복잡한 통계 처리를 위한 라이브러리
from scipy import stats

In [35]:
satisfaction = pd.read_csv('data/노인일자리사업_참여자_효과.csv', encoding='EUC-KR')
satisfaction.isna().sum()

satisfaction

       시점   특성별(1) 특성별(2)                 항목     데이터
0    2022       전체     소계             전체 (명)  3596.0
1    2022       전체     소계        여가시간 활용 (%)    11.5
2    2022       전체     소계        신체건강 유지 (%)    15.5
3    2022       전체     소계  외로움 해소(우울 예방) (%)     5.8
4    2022       전체     소계          소득 증가 (%)    56.6
..    ...      ...    ...                ...     ...
254  2022  사업참여상태별    대기자        신체건강 유지 (%)    10.7
255  2022  사업참여상태별    대기자  외로움 해소(우울 예방) (%)     5.4
256  2022  사업참여상태별    대기자          소득 증가 (%)    65.6
257  2022  사업참여상태별    대기자  일을 통한 보람과 즐거움 (%)     4.8
258  2022  사업참여상태별    대기자             기타 (%)     0.3

[259 rows x 5 columns]

In [37]:
satisfaction['특성별(1)'].unique()

# 컬럼명 변경
satisfaction.rename(columns={
    '특성별(1)': '분류',
    '특성별(2)': '유형별'
}, inplace=True)
satisfaction

       시점       분류  유형별                 항목     데이터
0    2022       전체   소계             전체 (명)  3596.0
1    2022       전체   소계        여가시간 활용 (%)    11.5
2    2022       전체   소계        신체건강 유지 (%)    15.5
3    2022       전체   소계  외로움 해소(우울 예방) (%)     5.8
4    2022       전체   소계          소득 증가 (%)    56.6
..    ...      ...  ...                ...     ...
254  2022  사업참여상태별  대기자        신체건강 유지 (%)    10.7
255  2022  사업참여상태별  대기자  외로움 해소(우울 예방) (%)     5.4
256  2022  사업참여상태별  대기자          소득 증가 (%)    65.6
257  2022  사업참여상태별  대기자  일을 통한 보람과 즐거움 (%)     4.8
258  2022  사업참여상태별  대기자             기타 (%)     0.3

[259 rows x 5 columns]

In [39]:
satisfaction.query('분류 == "연령별" and 항목 != "전체 (명)"')

       시점   분류     유형별                 항목   데이터
78   2022  연령별  60~64세        여가시간 활용 (%)  14.8
79   2022  연령별  60~64세        신체건강 유지 (%)  10.3
80   2022  연령별  60~64세  외로움 해소(우울 예방) (%)   4.0
81   2022  연령별  60~64세          소득 증가 (%)  57.3
82   2022  연령별  60~64세  일을 통한 보람과 즐거움 (%)  13.5
83   2022  연령별  60~64세             기타 (%)   0.2
85   2022  연령별  65~69세        여가시간 활용 (%)  12.1
86   2022  연령별  65~69세        신체건강 유지 (%)  12.0
87   2022  연령별  65~69세  외로움 해소(우울 예방) (%)   5.7
88   2022  연령별  65~69세          소득 증가 (%)  58.0
89   2022  연령별  65~69세  일을 통한 보람과 즐거움 (%)  12.0
90   2022  연령별  65~69세             기타 (%)   0.2
92   2022  연령별  70~74세        여가시간 활용 (%)  10.0
93   2022  연령별  70~74세        신체건강 유지 (%)  15.4
94   2022  연령별  70~74세  외로움 해소(우울 예방) (%)   5.2
95   2022  연령별  70~74세          소득 증가 (%)  58.2
96   2022  연령별  70~74세  일을 통한 보람과 즐거움 (%)  11.0
97   2022  연령별  70~74세             기타 (%)   0.2
99   2022  연령별  75세 이상        여가시간 활용 (%)  11.8
100  2022  연령별  75세 이상        신체건강 유지 (%)  16.7
101  2022  연령별  75세 이상  외로움 해소(우울 예방) (%)   6.2
102  2022  연령별  75세 이상          소득 증가 (%)  55.6
103  2022  연령별  75세 이상  일을 통한 보람과 즐거움 (%)   9.6
104  2022  연령별  75세 이상             기타 (%)   0.1

In [68]:
filtered = satisfaction.query('분류 == "전체" and 항목 != "전체 (명)"')

filtered.to_csv('노인일자리_참여효과설문_전체.csv', encoding='utf-8-sig', index=False)

In [61]:
working = pd.read_csv('data/노인의_현재_일을_하는_이유.csv', encoding='EUC-KR')
working

working.rename(columns={
    '특성(1)': '분류',
    '특성(2)': '유형별',
    '분류(1)' : '항목'
}, inplace=True)
working

       시점     분류    유형별             항목     데이터
0    2023     전체     소계       응답자수 (명)  3926.0
1    2023     전체     소계     생계비 마련 (%)    77.9
2    2023     전체     소계      용돈 필요 (%)     6.9
3    2023     전체     소계      건강 유지 (%)     6.2
4    2023     전체     소계      친교·사교 (%)     2.0
..    ...    ...    ...            ...     ...
256  2023  기능상태별  제한 없음      친교·사교 (%)     2.0
257  2023  기능상태별  제한 없음  능력(경력) 발휘 (%)     3.7
258  2023  기능상태별  제한 없음     시간 보내기 (%)     3.2
259  2023  기능상태별  제한 없음     사회적 기여 (%)     0.2
260  2023  기능상태별  제한 없음         기타 (%)     0.2

[261 rows x 5 columns]

In [63]:
working.query('분류 == "전체" and 유형별 == "소계" and 항목 != "응답자수 (명)"')

     시점  분류 유형별             항목   데이터
1  2023  전체  소계     생계비 마련 (%)  77.9
2  2023  전체  소계      용돈 필요 (%)   6.9
3  2023  전체  소계      건강 유지 (%)   6.2
4  2023  전체  소계      친교·사교 (%)   2.0
5  2023  전체  소계  능력(경력) 발휘 (%)   3.6
6  2023  전체  소계     시간 보내기 (%)   3.1
7  2023  전체  소계     사회적 기여 (%)   0.2
8  2023  전체  소계         기타 (%)   0.2

In [65]:
filtered = working.query('분류 == "전체" and 유형별 == "소계" and 항목 != "응답자수 (명)"')

filtered.to_csv('노인_일을_하는_이유.csv', encoding='utf-8-sig', index=False)