In [1]:
# 기본 라이브러리
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 그래프 기본 테마 설정
# https://coldbrown.co.kr/2023/07/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%8B%A4%EC%A0%84%ED%8E%B8-08-seaborn-sns-set%EC%9D%84-%ED%86%B5%ED%95%B4-%EC%8A%A4%ED%83%80%EC%9D%BC-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0/
sns.set()

# 그래프 기본 설정
plt.rcParams['font.family'] = 'Malgun Gothic'
# plt.rcParams['font.family'] = 'AppleGothic'
plt.rcParams['figure.figsize'] = 12, 6
plt.rcParams['font.size'] = 14
plt.rcParams['axes.unicode_minus'] = False

# 복잡한 통계 처리를 위한 라이브러리
from scipy import stats

In [2]:
elderly_publicJobs = pd.read_csv('data/최근10년_시도_연령별_경제활동인구.csv', encoding='EUC-KR')
elderly_publicJobs['항목'].unique()
elderly_publicJobs

      시도별     연령계층별    시점            항목      데이터
0       계         계  2014  15세이상인구 (천명)  42795.0
1       계         계  2014   경제활동인구 (천명)  26836.0
2       계         계  2014  비경제활동인구 (천명)  15959.0
3       계         계  2014   경제활동참가율 (%)     62.7
4       계         계  2014       고용률 (%)     60.5
...   ...       ...   ...           ...      ...
9745  제주도  15 - 24세  2024  15세이상인구 (천명)     64.0
9746  제주도  15 - 24세  2024   경제활동인구 (천명)     19.0
9747  제주도  15 - 24세  2024  비경제활동인구 (천명)     44.0
9748  제주도  15 - 24세  2024   경제활동참가율 (%)     30.1
9749  제주도  15 - 24세  2024       고용률 (%)     28.8

[9750 rows x 5 columns]

In [3]:
elderly_publicJobs.query('시도별 != "계" and 연령계층별 == "60세이상" and 항목 == "고용률 (%)"')

elderly_publicJobs.isna().sum()

시도별      0
연령계층별    0
시점       0
항목       0
데이터      0
dtype: int64

In [4]:
# 조건 적용: 시도별이 전국이고, 성별이 계, 연령별이 계인 데이터만 추출
filtered = elderly_publicJobs.query('시도별 != "계" and 연령계층별 == "60세이상" and 항목 == "고용률 (%)"')

# 해당 조건 반영된 데이터만 CSV로 저장
filtered.to_csv('시도_연도별_60세이상_고용률.csv', encoding='utf-8-sig', index=False)